site_name: pycounts documentation
theme:
  name: material
nav:
  - Home: index.md
  - Usage: example.ipynb
  - API Reference: api.md
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_submodules: true
  - mkdocs-jupyter:
      execute: true